---
# debugging task
# - debug: var=playbook_dir

# grab the folder names
- name: Store folder names in var
  command: ls /tmp/testing/test_ansible
  register: test_folders

# register a directories var
- name: Getting the stats of directories in specific folder
  stat: path="/tmp/testing/test_ansible/{{ item }}"
  with_items: "{{ test_folders.stdout_lines }}"
  register: st

- debug: var="{{ item }}"
  with_items: "{{ st.results }}"

# print the directories stats


# move directories older than 6 months+ in another folder


# symlink the moved directories back to the previous folder