---
# debugging task
# - debug: var=playbook_dir

- name: Find the test dirs created in the past
  find: >
    paths=/home/dminca/Pictures
    age=2w
  register: test_dirs

- debug: var={{ item[1] }}
  with_indexed_items: "{{ test_dirs.files }}"
