---
- name: install docker
  apt:
    package: docker-engine
    update_cache: true
    state: latest
  notify: start docker

- name: install docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'

- name: install docker machine
  get_url:
    url: "https://github.com/docker/machine/releases/download/v{{ docker_machine_version }}/docker-machine-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-machine
    mode: 'u+x'
    checksum: "{{ docker_machine_checksum }}"
